### ISSUE TITLE
이지롤 블라인드 1.9 버전 오류

### ISSUE THREAD

**Issue by saya6k** [iluna8/ha-addons#1]
Home Assistant 2023.7.2
Supervisor 2023.07.1
Operating System 10.3
베어메탈 환경.

파이썬 모듈이 없다고 나오는 것 같습니다.

혹시 해결 방법이 있을까요?

running easyroll smart blind addon...
internal/modules/cjs/loader.js:934
  throw err;
  ^
Error: Cannot find module 'request'
Require stack:
- /share/easyroll/easyroll_blind.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:931:15)
    at Function.Module._load (internal/modules/cjs/loader.js:774:27)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/share/easyroll/easyroll_blind.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/share/easyroll/easyroll_blind.js' ]
}

**Comment by lunDreame** [comment]
파일 업데이트가 안되서 그래요. /share/easyroll/easyroll_blind.js 파일 지우시고 애드온 재시작하시면 동작할거에요.

**Comment by saya6k** [comment]
예 되네요 감사합니다!
